### PR TITLE
Moving things around

### PR DESCRIPTION
**Pull request by ambroggi**
Moved a lot of the code around, removed the resilience folder into the main folder. Added tests to check that things are working properly.

### CODE REVIEW

**Comment by ambroggi** [comment]
Pause this for now, I am checking something.

**Comment by ambroggi** [comment]
It is working now, just a small problem with DOC.

**Comment by ambroggi** [comment]
Nope, still not working... Sorry.

**Comment by bayegaspard** [comment]
Thank you !

**Pull request merged**
